name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://migamake/stack-build-image:17.0
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
      - run: stack build