name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://migamake/stack-build-image:17.0
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: "ALL"
          path: |
            .stack-work/
            /home/runner/.stack
      - run: curl -L https://nixos.org/nix/install | sh
      - run: stack test